# Generated by Django 2.2 on 2019-06-12 01:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190526_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='renewed',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.Client'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 6, 12)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service',
            field=models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.DO_NOTHING, to='services.Service'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 6, 12)),
        ),
    ]
