# Generated by Django 2.2 on 2019-06-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20190612_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='renewed',
            field=models.DateField(default=None, null=True),
        ),
    ]
