# Generated by Django 2.2 on 2019-06-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20190612_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='renewed',
        ),
    ]
