# Generated by Django 2.2 on 2019-06-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_contract_renewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='renewed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
