# Generated by Django 2.2 on 2019-06-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_contract_renewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='renewed',
            field=models.DateField(),
        ),
    ]
