# Generated by Django 2.2 on 2019-05-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20190504_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
