# Generated by Django 2.2 on 2019-05-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_person_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Client',
        ),
    ]
