# Generated by Django 2.2 on 2019-05-08 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20190508_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Address'),
        ),
    ]
